Q1. What are the benefits of the built-in array package, if any?

ans: the benefits are as follows:
     
     1. Get Size of Array Item
     
     2. Count the Number of Occurrences of elements in the array
     
     3. Append and Extend values in arrays
     
     4. Manipulating the Index of the elements in the array
     
     5. converting Array to List.

Q2. What are some of the array package's limitations?

ans. the follwoing are the limitation of array packages:
    
    1.  built-in array module, when the desired datatype of the array was int and float value was passed to the array. A TypeError occurred ‘integer argument expected got float’.
    
    2. This is the major difference between the built-in array module and numpy array. A built-in array is quite strict about the storage of objects in itself. It permits only that type of data to be stored in itself, which has been specified strictly by the typecode. We could not store float value when typecode specified that, int data has to be stored in the built-in array

Q3. Describe the main differences between the array and numpy packages.

ans: the main difference between the array and numpy packages are as follows:
        
    1.In built-in array module, when the desired datatype of the array was int and float value was passed to the array. A TypeError occurred ‘integer argument expected got float’. And inbuilt array module when the desired data type of array was Unicode character specified by typecode ‘u’, and the floating value was sent to array. TypeError occurred that ‘array item must be Unicode character’. But in numpy array when the desired data type of array was int and float value was sent to array. Float values were typecasted into an int (with loss of data after the decimal) and when the desired data type of array was string and float value were sent to an array, float values were typecasted into a string. 
    
    2. This is the major difference between the built-in array module and numpy array. A built-in array is quite strict about the storage of objects in itself. It permits only that type of data to be stored in itself, which has been specified strictly by the typecode. We could not store float value when typecode specified that, int data has to be stored in the built-in array. However numpy array is a bit tolerant or lenient in that matter, it will upcast or downcast and try to store the data at any cost. (Float was converted to int, even if that resulted in loss of data after decimal)

Q4. Explain the distinctions between the empty, ones, and zeros functions.

In [3]:
import numpy as np
#np.zeros=Return a new array setting values to zero.
np.zeros((2,2))





array([[0., 0.],
       [0., 0.]])

In [4]:
#np.empty=Return a new uninitialized array.
np.empty((2,2))

array([[0., 0.],
       [0., 0.]])

In [6]:
#np.zeros=Return a new array setting values to one.
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable
argument?

ans: the callable arguments in the np.fromfunction() consists of function, shape,  dtype.

In [7]:
np.fromfunction(lambda i,j:i==j,(3,3),dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as
an int or a floating-point value) through addition, as in the expression A + n?

In [13]:
np.array(([2,2],[3,3]))

array([[2, 2],
       [3, 3]])

In [14]:
np.array(([2,2],[3,3]))+1

array([[3, 3],
       [4, 4]])

Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)?
What is the outcome?

In [15]:
np.array(([2,2],[3,3])) +=1

SyntaxError: 'function call' is an illegal expression for augmented assignment (1059903085.py, line 1)

In [16]:
np.array(([2,2],[3,3])) *=2

SyntaxError: 'function call' is an illegal expression for augmented assignment (1526065479.py, line 1)

Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to
one of these arrays?

In [20]:
np.array(["jbcabvaj"])

array(['jbcabvaj'], dtype='<U8')

ans: yes, numpy array contain fixed lenght strings.The dtype of any numpy array containing string values is the maximum length of any string present in the array. Once set, it will only be able to store new string having length not more than the maximum length at the time of the creation. If we try to reassign some another string value having length greater than the maximum length of the existing elements, it simply discards all the values beyond the maximum length.

Q9. What happens when you combine two numpy arrays using an operation like addition (+) or
multiplication (*)? What are the conditions for combining two numpy arrays?

In [24]:
arr1=np.array([[1,2],[3,4]])

In [23]:
arr2=np.array([[5,6],[7,8]])

In [25]:
arr1+arr2

array([[ 6,  8],
       [10, 12]])

In [26]:
arr1*arr2

array([[ 5, 12],
       [21, 32]])

ans: corresponding values of  both the arrays will be added and multiplicated if addition or multiply takes place beween the two arrays respectively

Q10. What is the best way to use a Boolean array to mask another array?

In [27]:
arr1


array([[1, 2],
       [3, 4]])

In [28]:
arr2

array([[5, 6],
       [7, 8]])

In [30]:
mask = np.ma.masked_where(arr2,arr1)

In [31]:
print(mask)

[[-- --]
 [-- --]]


Q11. What are three different ways to get the standard deviation of a wide collection of data using
both standard Python and its packages? Sort the three of them by how quickly they execute.

ans: The following three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages :-
    
    1. numpy package np.std
    
    2. statistics package- statistics.stdev()
    
   
     

12. What is the dimensionality of a Boolean mask-generated array?

Ans: It will have same dimensionality as input array.